### ISSUE TITLE
timeout support

### ISSUE THREAD

**Issue by pcmid** [nadoo/ipset#1]
Do there have any plan to add optional timeout parameter? I think it will be useful on dispatching by dns.

**Comment by nadoo** [comment]
Do you mean the timeout option of ipset? https://ipset.netfilter.org/ipset.man.html#lbAJ

This package is used in glider, it always update the ipset without timeout, to make the ip rules permanent(as the domain rules in config file are permanent), could you please describe the scenarios which are useful?

**Comment by pcmid** [comment]
If some domain has dynamic ip, such as be proxied by cloudflare, how we can update the ipset automatically? Therefore timeout should be useful in this situation.

**Comment by ihipop** [comment]
ipset has an item ttl feature，if the ttl of some item is expired，the item will be auto deleted from that set

**Comment by nadoo** [comment]
added in v0.4.0
